### ISSUE TITLE
openfortivpn-webview-qt can not be built with Ubuntu 24.04

### ISSUE THREAD

**Issue by bmaehr** [gm-vm/openfortivpn-webview#44]
```
In file included from webauthdialog.cpp:4:
webauthdialog.h:10:10: fatal error: QWebEngineWebAuthUxRequest: No such file or directory
   10 | #include <QWebEngineWebAuthUxRequest>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

QWebEngineWebAuthUxRequest was added in Qt 6.6, will try Ubuntu 24.10

**Comment by gm-vm** [comment]
My bad, I remembered to add the ifdefs here and there, but not to exclude the source files from qmake/cmake. I should add conditions there.

**Comment by gm-vm** [comment]
By the way, in the meantime you can checkout commit 894c3e94ecd99bd8aeca9f43495e1d6e3cdafc9b and build the app from there.

**Comment by gm-vm** [comment]
Fixed with cc832afed74bd6676d862d74410a83db80ddbbb5.

**Comment by bmaehr** [comment]
It is still not solved for Qt 6.6.2 (Ubuntu 24.10) but works for Qt 6.8.

**Comment by bmaehr** [comment]
I think `greaterThan(QT_VERSION, 6.6) {` in your commit needs to be `greaterThan(QT_VERSION, 6.7) {`

**Comment by gm-vm** [comment]
Thanks, I fixed the condition in 3d2880db8c9ace04471a7e79fb5c380f2ec22ba8. The problem were the patch releases, such as 6.6.

**Comment by bmaehr** [comment]
I don't know if I should open a new issue for this:

```
Sandboxing disabled by user.
[New Thread 0x7fffcb6006c0 (LWP 687489)]
[Detaching after fork from child process 687490]
[Detaching after fork from child process 687491]
[New Thread 0x7fffcac006c0 (LWP 687492)]
[New Thread 0x7fffca2006c0 (LWP 687493)]
[New Thread 0x7fffc98006c0 (LWP 687494)]
[New Thread 0x7fffc3e006c0 (LWP 687495)]
[New Thread 0x7fffc8e006c0 (LWP 687496)]
[New Thread 0x7fffc2a006c0 (LWP 687498)]
[New Thread 0x7fffc34006c0 (LWP 687497)]
[New Thread 0x7fffc20006c0 (LWP 687499)]
[New Thread 0x7fffc16006c0 (LWP 687500)]
[New Thread 0x7fffb7e006c0 (LWP 687502)]
[New Thread 0x7fffc0c006c0 (LWP 687501)]
[New Thread 0x7fffb74006c0 (LWP 687503)]
[New Thread 0x7fffb6a006c0 (LWP 687504)]
[New Thread 0x7fffb60006c0 (LWP 687505)]

Thread 1 "openfortivpn-we" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fa4b7d in ?? () from /lib/x86_64-linux-gnu/libQt6WebEngineWidgets.so.6
(gdb) bt
#0  0x00007ffff7fa4b7d in ?? () from /lib/x86_64-linux-gnu/libQt6WebEngineWidgets.so.6
#1  0x00007ffff7fa5de9 in QWebEngineView::setPage(QWebEnginePage*) () from /lib/x86_64-linux-gnu/libQt6WebEngineWidgets.so.6
#2  0x000055555555de13 in MainWindow::MainWindow (this=this@entry=0x7fffffffe0f0, keepOpen=keepOpen@entry=false, urlToWaitForRegex=..., certificateHashToTrust=..., parent=parent@entry=0x0)
    at mainwindow.cpp:34
#3  0x000055555555c0fe in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qarraydata.h:53

```

**Comment by gm-vm** [comment]
Ugh, that was a dumb mistake. I was trying the changes from a virtual machine and copied them manually on my main machine to push them. Apparently I accidentally removed a line during this process 4018e3b0229175cf5395dbf4f722f3d478902a9a
